<?php 
$user = $this->user;
$albums = $this->albums;
?>

<div class="row-fluid">
	<div class="span11 englober" >
	<?php 
	if($albums){
		?>
		<ul class="thumbnails upload-thumbnails">
		<?php 
		//on commence par créer par l'image par défaut si elle n'existe pas
		$path_parts = pathinfo('img/appareil-photo.jpg');
		$defaultImageMin = $path_parts['dirname'].'/'.$path_parts['filename'].'.minH120.'.$path_parts['extension'];
		if(!file_exists($defaultImageMin)) {
			$defaultImageMin = redimJPEG('img/appareil-photo.jpg', 120, 'H');
		}
		//ensuite on affiche les albums
		foreach ($albums as $album){
			if($album instanceof Bdmap_Album){
				//recuperer la premiere photo de l'abum courant
				$photo = Gestionnaire::getGestionnaire('photo')->getOf(array('id_album' => $album->getId()),'id',false,0,1);
				$photo = $photo[0];
				if($photo instanceof Bdmap_Photo) {
					$img = $photo->getMinUrl();
					if($img === false){
						$img = $defaultImageMin;
					}
				}
				else {
					$img = $defaultImageMin;
				}
				?>
				<li class="span3">
					<div class="thumbnail">
						<img src="<?php echo $img; ?>" class="span12 listeAlbum" />
						<span class="span12">
							<?php echo $album->getNom(); ?>
						</span>
					</div>
				</li>
				<?php 
			}
		}
		?>
		</ul>
		<?php 
	}
	else {
	?>
	<div class="span12">Vous n'avez pas encore d'album.</div>
	<?php 
	}
	?>
	</div>
</div>